version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config/local.yaml
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=url-shortener_user
      - DB_PASSWORD=url-shortener_pass
      - DB_NAME=url-shortener_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: url-shortener_db
      POSTGRES_USER: url-shortener_user
      POSTGRES_PASSWORD: url-shortener_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: