version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: url-shortener-postgres
    environment:
      POSTGRES_DB: url-shortener_db
      POSTGRES_USER: url-shortener_user
      POSTGRES_PASSWORD: url-shortener_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: