env: "local"

http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
  user: my_user
  password: my_password

postgres:
  host: postgres
  port: 5432
  user: "url-shortener_user"
  password: "url-shortener_pass"
  dbname: "url-shortener_db"
  sslmode: "disable"