env: "local"

postgres:
  host: localhost
  port: 5432
  dbname: "url-shortener_db"
  user: "url-shortener_user"
  password: "url-shortener_pass"
  sslmode: "disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s